#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Name
No description available.
.PARAMETER DisplayName
No description available.
.PARAMETER Currency
No description available.
.PARAMETER VatRate
No description available.
.PARAMETER MarketPrefix
No description available.
.PARAMETER CountryId
No description available.
.PARAMETER CurrencyId
No description available.
.PARAMETER CurrencyRate
No description available.
.PARAMETER LanguageId
No description available.
.PARAMETER Language
No description available.
.OUTPUTS

MarketModelsMarket<PSCustomObject>
#>

function Initialize-MarketModelsMarket {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayName},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Currency},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${VatRate},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MarketPrefix},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${CountryId},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${CurrencyId},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${CurrencyRate},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${LanguageId},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Language}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => MarketModelsMarket' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "Id" = ${Id}
            "Name" = ${Name}
            "DisplayName" = ${DisplayName}
            "Currency" = ${Currency}
            "VatRate" = ${VatRate}
            "MarketPrefix" = ${MarketPrefix}
            "CountryId" = ${CountryId}
            "CurrencyId" = ${CurrencyId}
            "CurrencyRate" = ${CurrencyRate}
            "LanguageId" = ${LanguageId}
            "Language" = ${Language}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to MarketModelsMarket<PSCustomObject>

.DESCRIPTION

Convert from JSON to MarketModelsMarket<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

MarketModelsMarket<PSCustomObject>
#>
function ConvertFrom-JsonToMarketModelsMarket {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => MarketModelsMarket' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in MarketModelsMarket
        $AllProperties = ("Id", "Name", "DisplayName", "Currency", "VatRate", "MarketPrefix", "CountryId", "CurrencyId", "CurrencyRate", "LanguageId", "Language")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["Id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["Name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DisplayName"))) { #optional property not found
            $DisplayName = $null
        } else {
            $DisplayName = $JsonParameters.PSobject.Properties["DisplayName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Currency"))) { #optional property not found
            $Currency = $null
        } else {
            $Currency = $JsonParameters.PSobject.Properties["Currency"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "VatRate"))) { #optional property not found
            $VatRate = $null
        } else {
            $VatRate = $JsonParameters.PSobject.Properties["VatRate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "MarketPrefix"))) { #optional property not found
            $MarketPrefix = $null
        } else {
            $MarketPrefix = $JsonParameters.PSobject.Properties["MarketPrefix"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "CountryId"))) { #optional property not found
            $CountryId = $null
        } else {
            $CountryId = $JsonParameters.PSobject.Properties["CountryId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "CurrencyId"))) { #optional property not found
            $CurrencyId = $null
        } else {
            $CurrencyId = $JsonParameters.PSobject.Properties["CurrencyId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "CurrencyRate"))) { #optional property not found
            $CurrencyRate = $null
        } else {
            $CurrencyRate = $JsonParameters.PSobject.Properties["CurrencyRate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "LanguageId"))) { #optional property not found
            $LanguageId = $null
        } else {
            $LanguageId = $JsonParameters.PSobject.Properties["LanguageId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Language"))) { #optional property not found
            $Language = $null
        } else {
            $Language = $JsonParameters.PSobject.Properties["Language"].value
        }

        $PSO = [PSCustomObject]@{
            "Id" = ${Id}
            "Name" = ${Name}
            "DisplayName" = ${DisplayName}
            "Currency" = ${Currency}
            "VatRate" = ${VatRate}
            "MarketPrefix" = ${MarketPrefix}
            "CountryId" = ${CountryId}
            "CurrencyId" = ${CurrencyId}
            "CurrencyRate" = ${CurrencyRate}
            "LanguageId" = ${LanguageId}
            "Language" = ${Language}
        }

        return $PSO
    }

}

