#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER OrderRowId
No description available.
.PARAMETER ItemId
No description available.
.PARAMETER ProductId
No description available.
.PARAMETER Price
No description available.
.PARAMETER PriceExVat
No description available.
.PARAMETER Name
No description available.
.PARAMETER ProductName
No description available.
.PARAMETER Variant
No description available.
.PARAMETER Brand
No description available.
.OUTPUTS

OrderRefundRow<PSCustomObject>
#>

function Initialize-OrderRefundRow {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${OrderRowId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${ItemId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${ProductId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${Price},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${PriceExVat},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProductName},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Variant},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Brand}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OrderRefundRow' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "OrderRowId" = ${OrderRowId}
            "ItemId" = ${ItemId}
            "ProductId" = ${ProductId}
            "Price" = ${Price}
            "PriceExVat" = ${PriceExVat}
            "Name" = ${Name}
            "ProductName" = ${ProductName}
            "Variant" = ${Variant}
            "Brand" = ${Brand}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OrderRefundRow<PSCustomObject>

.DESCRIPTION

Convert from JSON to OrderRefundRow<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OrderRefundRow<PSCustomObject>
#>
function ConvertFrom-JsonToOrderRefundRow {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OrderRefundRow' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OrderRefundRow
        $AllProperties = ("OrderRowId", "ItemId", "ProductId", "Price", "PriceExVat", "Name", "ProductName", "Variant", "Brand")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "OrderRowId"))) { #optional property not found
            $OrderRowId = $null
        } else {
            $OrderRowId = $JsonParameters.PSobject.Properties["OrderRowId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ItemId"))) { #optional property not found
            $ItemId = $null
        } else {
            $ItemId = $JsonParameters.PSobject.Properties["ItemId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ProductId"))) { #optional property not found
            $ProductId = $null
        } else {
            $ProductId = $JsonParameters.PSobject.Properties["ProductId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Price"))) { #optional property not found
            $Price = $null
        } else {
            $Price = $JsonParameters.PSobject.Properties["Price"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "PriceExVat"))) { #optional property not found
            $PriceExVat = $null
        } else {
            $PriceExVat = $JsonParameters.PSobject.Properties["PriceExVat"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["Name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ProductName"))) { #optional property not found
            $ProductName = $null
        } else {
            $ProductName = $JsonParameters.PSobject.Properties["ProductName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Variant"))) { #optional property not found
            $Variant = $null
        } else {
            $Variant = $JsonParameters.PSobject.Properties["Variant"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Brand"))) { #optional property not found
            $Brand = $null
        } else {
            $Brand = $JsonParameters.PSobject.Properties["Brand"].value
        }

        $PSO = [PSCustomObject]@{
            "OrderRowId" = ${OrderRowId}
            "ItemId" = ${ItemId}
            "ProductId" = ${ProductId}
            "Price" = ${Price}
            "PriceExVat" = ${PriceExVat}
            "Name" = ${Name}
            "ProductName" = ${ProductName}
            "Variant" = ${Variant}
            "Brand" = ${Brand}
        }

        return $PSO
    }

}

