#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The API-representation of page widgets

.PARAMETER Id
The IDs of widgets are immutable (determined by each view model implementation, in the namespace Carismar.Core)
.PARAMETER Name
The static name of this widget. Used to translate into icons, or to append to css-classes.
.PARAMETER Type
The name of the widget-type
.PARAMETER Active
Decides if this {PageArea.Models.Read.PageWidget} is active or not
.PARAMETER ClassNames
Holds all CSS Class names that this widget should render
.PARAMETER Size
The fractional size for this widget in it's container.
.PARAMETER Configuration
The configuration for this {PageArea.Models.Read.PageWidget}
.OUTPUTS

PageAreaModelsReadPageWidget<PSCustomObject>
#>

function Initialize-PageAreaModelsReadPageWidget {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Active},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${ClassNames},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Size},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Configuration}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PageAreaModelsReadPageWidget' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "Id" = ${Id}
            "Name" = ${Name}
            "Type" = ${Type}
            "Active" = ${Active}
            "ClassNames" = ${ClassNames}
            "Size" = ${Size}
            "Configuration" = ${Configuration}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PageAreaModelsReadPageWidget<PSCustomObject>

.DESCRIPTION

Convert from JSON to PageAreaModelsReadPageWidget<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PageAreaModelsReadPageWidget<PSCustomObject>
#>
function ConvertFrom-JsonToPageAreaModelsReadPageWidget {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PageAreaModelsReadPageWidget' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PageAreaModelsReadPageWidget
        $AllProperties = ("Id", "Name", "Type", "Active", "ClassNames", "Size", "Configuration")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["Id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["Name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["Type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Active"))) { #optional property not found
            $Active = $null
        } else {
            $Active = $JsonParameters.PSobject.Properties["Active"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ClassNames"))) { #optional property not found
            $ClassNames = $null
        } else {
            $ClassNames = $JsonParameters.PSobject.Properties["ClassNames"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Size"))) { #optional property not found
            $Size = $null
        } else {
            $Size = $JsonParameters.PSobject.Properties["Size"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Configuration"))) { #optional property not found
            $Configuration = $null
        } else {
            $Configuration = $JsonParameters.PSobject.Properties["Configuration"].value
        }

        $PSO = [PSCustomObject]@{
            "Id" = ${Id}
            "Name" = ${Name}
            "Type" = ${Type}
            "Active" = ${Active}
            "ClassNames" = ${ClassNames}
            "Size" = ${Size}
            "Configuration" = ${Configuration}
        }

        return $PSO
    }

}

