#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CollectionName
No description available.
.PARAMETER EnableLazyloadMobile
No description available.
.PARAMETER EagerLoadStepsMobile
No description available.
.PARAMETER EnableLazyloadDesktop
No description available.
.PARAMETER EagerLoadStepsDesktop
No description available.
.OUTPUTS

PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration<PSCustomObject>
#>

function Initialize-PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CollectionName},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableLazyloadMobile},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${EagerLoadStepsMobile},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableLazyloadDesktop},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${EagerLoadStepsDesktop}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "CollectionName" = ${CollectionName}
            "EnableLazyloadMobile" = ${EnableLazyloadMobile}
            "EagerLoadStepsMobile" = ${EagerLoadStepsMobile}
            "EnableLazyloadDesktop" = ${EnableLazyloadDesktop}
            "EagerLoadStepsDesktop" = ${EagerLoadStepsDesktop}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration<PSCustomObject>

.DESCRIPTION

Convert from JSON to PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration<PSCustomObject>
#>
function ConvertFrom-JsonToPageWidgetLazyLoadSetupLazyLoadCollectionConfiguration {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PageWidgetLazyLoadSetupLazyLoadCollectionConfiguration
        $AllProperties = ("CollectionName", "EnableLazyloadMobile", "EagerLoadStepsMobile", "EnableLazyloadDesktop", "EagerLoadStepsDesktop")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "CollectionName"))) { #optional property not found
            $CollectionName = $null
        } else {
            $CollectionName = $JsonParameters.PSobject.Properties["CollectionName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "EnableLazyloadMobile"))) { #optional property not found
            $EnableLazyloadMobile = $null
        } else {
            $EnableLazyloadMobile = $JsonParameters.PSobject.Properties["EnableLazyloadMobile"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "EagerLoadStepsMobile"))) { #optional property not found
            $EagerLoadStepsMobile = $null
        } else {
            $EagerLoadStepsMobile = $JsonParameters.PSobject.Properties["EagerLoadStepsMobile"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "EnableLazyloadDesktop"))) { #optional property not found
            $EnableLazyloadDesktop = $null
        } else {
            $EnableLazyloadDesktop = $JsonParameters.PSobject.Properties["EnableLazyloadDesktop"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "EagerLoadStepsDesktop"))) { #optional property not found
            $EagerLoadStepsDesktop = $null
        } else {
            $EagerLoadStepsDesktop = $JsonParameters.PSobject.Properties["EagerLoadStepsDesktop"].value
        }

        $PSO = [PSCustomObject]@{
            "CollectionName" = ${CollectionName}
            "EnableLazyloadMobile" = ${EnableLazyloadMobile}
            "EagerLoadStepsMobile" = ${EagerLoadStepsMobile}
            "EnableLazyloadDesktop" = ${EnableLazyloadDesktop}
            "EagerLoadStepsDesktop" = ${EagerLoadStepsDesktop}
        }

        return $PSO
    }

}

