#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Contains pagination information for paged operations, i.e. PageSize and PageCount.

.PARAMETER BatchId
The id of the batch operation. If this property has a value for the first fetched page it has to be passed as a parameter for all subsequent requests-
.PARAMETER Page
The current page
.PARAMETER RowCount
Total number of rows
.PARAMETER PageCount
Total number of pages
.PARAMETER PageSize
Page size
.PARAMETER HasMoreRows
True if there is more content to fetch.
.OUTPUTS

PageResult<PSCustomObject>
#>

function Initialize-PageResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BatchId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Page},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${RowCount},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${PageCount},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${PageSize},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HasMoreRows}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PageResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "BatchId" = ${BatchId}
            "Page" = ${Page}
            "RowCount" = ${RowCount}
            "PageCount" = ${PageCount}
            "PageSize" = ${PageSize}
            "HasMoreRows" = ${HasMoreRows}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PageResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to PageResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PageResult<PSCustomObject>
#>
function ConvertFrom-JsonToPageResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PageResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PageResult
        $AllProperties = ("BatchId", "Page", "RowCount", "PageCount", "PageSize", "HasMoreRows")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "BatchId"))) { #optional property not found
            $BatchId = $null
        } else {
            $BatchId = $JsonParameters.PSobject.Properties["BatchId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Page"))) { #optional property not found
            $Page = $null
        } else {
            $Page = $JsonParameters.PSobject.Properties["Page"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "RowCount"))) { #optional property not found
            $RowCount = $null
        } else {
            $RowCount = $JsonParameters.PSobject.Properties["RowCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "PageCount"))) { #optional property not found
            $PageCount = $null
        } else {
            $PageCount = $JsonParameters.PSobject.Properties["PageCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "PageSize"))) { #optional property not found
            $PageSize = $null
        } else {
            $PageSize = $JsonParameters.PSobject.Properties["PageSize"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "HasMoreRows"))) { #optional property not found
            $HasMoreRows = $null
        } else {
            $HasMoreRows = $JsonParameters.PSobject.Properties["HasMoreRows"].value
        }

        $PSO = [PSCustomObject]@{
            "BatchId" = ${BatchId}
            "Page" = ${Page}
            "RowCount" = ${RowCount}
            "PageCount" = ${PageCount}
            "PageSize" = ${PageSize}
            "HasMoreRows" = ${HasMoreRows}
        }

        return $PSO
    }

}

