#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER PaymentId
No description available.
.PARAMETER PaymentGroupId
No description available.
.PARAMETER Name
No description available.
.PARAMETER DisplayName
No description available.
.PARAMETER Fee
No description available.
.PARAMETER Icon
No description available.
.PARAMETER Sort
No description available.
.PARAMETER Period
No description available.
.PARAMETER TermsLink
No description available.
.PARAMETER InfoLink
No description available.
.PARAMETER PersonalIdRequired
No description available.
.PARAMETER RegisteredAddressRequired
No description available.
.PARAMETER HouseNumberRequired
No description available.
.PARAMETER HouseExtensionShown
No description available.
.PARAMETER GenderRequired
No description available.
.PARAMETER BirthdateRequired
No description available.
.OUTPUTS

PaymentModelsPaymentOption<PSCustomObject>
#>

function Initialize-PaymentModelsPaymentOption {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${PaymentId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${PaymentGroupId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayName},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${Fee},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Icon},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Sort},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Period},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TermsLink},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${InfoLink},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${PersonalIdRequired},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${RegisteredAddressRequired},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HouseNumberRequired},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HouseExtensionShown},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${GenderRequired},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BirthdateRequired}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PaymentModelsPaymentOption' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "PaymentId" = ${PaymentId}
            "PaymentGroupId" = ${PaymentGroupId}
            "Name" = ${Name}
            "DisplayName" = ${DisplayName}
            "Fee" = ${Fee}
            "Icon" = ${Icon}
            "Sort" = ${Sort}
            "Period" = ${Period}
            "TermsLink" = ${TermsLink}
            "InfoLink" = ${InfoLink}
            "PersonalIdRequired" = ${PersonalIdRequired}
            "RegisteredAddressRequired" = ${RegisteredAddressRequired}
            "HouseNumberRequired" = ${HouseNumberRequired}
            "HouseExtensionShown" = ${HouseExtensionShown}
            "GenderRequired" = ${GenderRequired}
            "BirthdateRequired" = ${BirthdateRequired}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PaymentModelsPaymentOption<PSCustomObject>

.DESCRIPTION

Convert from JSON to PaymentModelsPaymentOption<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PaymentModelsPaymentOption<PSCustomObject>
#>
function ConvertFrom-JsonToPaymentModelsPaymentOption {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PaymentModelsPaymentOption' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PaymentModelsPaymentOption
        $AllProperties = ("PaymentId", "PaymentGroupId", "Name", "DisplayName", "Fee", "Icon", "Sort", "Period", "TermsLink", "InfoLink", "PersonalIdRequired", "RegisteredAddressRequired", "HouseNumberRequired", "HouseExtensionShown", "GenderRequired", "BirthdateRequired")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "PaymentId"))) { #optional property not found
            $PaymentId = $null
        } else {
            $PaymentId = $JsonParameters.PSobject.Properties["PaymentId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "PaymentGroupId"))) { #optional property not found
            $PaymentGroupId = $null
        } else {
            $PaymentGroupId = $JsonParameters.PSobject.Properties["PaymentGroupId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["Name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DisplayName"))) { #optional property not found
            $DisplayName = $null
        } else {
            $DisplayName = $JsonParameters.PSobject.Properties["DisplayName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Fee"))) { #optional property not found
            $Fee = $null
        } else {
            $Fee = $JsonParameters.PSobject.Properties["Fee"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Icon"))) { #optional property not found
            $Icon = $null
        } else {
            $Icon = $JsonParameters.PSobject.Properties["Icon"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Sort"))) { #optional property not found
            $Sort = $null
        } else {
            $Sort = $JsonParameters.PSobject.Properties["Sort"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Period"))) { #optional property not found
            $Period = $null
        } else {
            $Period = $JsonParameters.PSobject.Properties["Period"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "TermsLink"))) { #optional property not found
            $TermsLink = $null
        } else {
            $TermsLink = $JsonParameters.PSobject.Properties["TermsLink"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "InfoLink"))) { #optional property not found
            $InfoLink = $null
        } else {
            $InfoLink = $JsonParameters.PSobject.Properties["InfoLink"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "PersonalIdRequired"))) { #optional property not found
            $PersonalIdRequired = $null
        } else {
            $PersonalIdRequired = $JsonParameters.PSobject.Properties["PersonalIdRequired"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "RegisteredAddressRequired"))) { #optional property not found
            $RegisteredAddressRequired = $null
        } else {
            $RegisteredAddressRequired = $JsonParameters.PSobject.Properties["RegisteredAddressRequired"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "HouseNumberRequired"))) { #optional property not found
            $HouseNumberRequired = $null
        } else {
            $HouseNumberRequired = $JsonParameters.PSobject.Properties["HouseNumberRequired"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "HouseExtensionShown"))) { #optional property not found
            $HouseExtensionShown = $null
        } else {
            $HouseExtensionShown = $JsonParameters.PSobject.Properties["HouseExtensionShown"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "GenderRequired"))) { #optional property not found
            $GenderRequired = $null
        } else {
            $GenderRequired = $JsonParameters.PSobject.Properties["GenderRequired"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "BirthdateRequired"))) { #optional property not found
            $BirthdateRequired = $null
        } else {
            $BirthdateRequired = $JsonParameters.PSobject.Properties["BirthdateRequired"].value
        }

        $PSO = [PSCustomObject]@{
            "PaymentId" = ${PaymentId}
            "PaymentGroupId" = ${PaymentGroupId}
            "Name" = ${Name}
            "DisplayName" = ${DisplayName}
            "Fee" = ${Fee}
            "Icon" = ${Icon}
            "Sort" = ${Sort}
            "Period" = ${Period}
            "TermsLink" = ${TermsLink}
            "InfoLink" = ${InfoLink}
            "PersonalIdRequired" = ${PersonalIdRequired}
            "RegisteredAddressRequired" = ${RegisteredAddressRequired}
            "HouseNumberRequired" = ${HouseNumberRequired}
            "HouseExtensionShown" = ${HouseExtensionShown}
            "GenderRequired" = ${GenderRequired}
            "BirthdateRequired" = ${BirthdateRequired}
        }

        return $PSO
    }

}

