#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A price list definition.

.PARAMETER Id
Price list id.
.PARAMETER Name
Price list name.
.PARAMETER MarketId
Market id.
.PARAMETER MarketPrefix
Market prefix.  <example>Eg: SE</example>
.PARAMETER Currency
Currency abbreviation.  <example>Eg: SEK</example>
.OUTPUTS

PriceListModelsPriceList<PSCustomObject>
#>

function Initialize-PriceListModelsPriceList {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MarketId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MarketPrefix},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Currency}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PriceListModelsPriceList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "Id" = ${Id}
            "Name" = ${Name}
            "MarketId" = ${MarketId}
            "MarketPrefix" = ${MarketPrefix}
            "Currency" = ${Currency}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PriceListModelsPriceList<PSCustomObject>

.DESCRIPTION

Convert from JSON to PriceListModelsPriceList<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PriceListModelsPriceList<PSCustomObject>
#>
function ConvertFrom-JsonToPriceListModelsPriceList {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PriceListModelsPriceList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PriceListModelsPriceList
        $AllProperties = ("Id", "Name", "MarketId", "MarketPrefix", "Currency")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["Id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["Name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "MarketId"))) { #optional property not found
            $MarketId = $null
        } else {
            $MarketId = $JsonParameters.PSobject.Properties["MarketId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "MarketPrefix"))) { #optional property not found
            $MarketPrefix = $null
        } else {
            $MarketPrefix = $JsonParameters.PSobject.Properties["MarketPrefix"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Currency"))) { #optional property not found
            $Currency = $null
        } else {
            $Currency = $JsonParameters.PSobject.Properties["Currency"].value
        }

        $PSO = [PSCustomObject]@{
            "Id" = ${Id}
            "Name" = ${Name}
            "MarketId" = ${MarketId}
            "MarketPrefix" = ${MarketPrefix}
            "Currency" = ${Currency}
        }

        return $PSO
    }

}

