#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SiteId
No description available.
.PARAMETER LanguageCode
No description available.
.PARAMETER Email
No description available.
.PARAMETER SkuId
No description available.
.OUTPUTS

ProductModelsMonitorSku<PSCustomObject>
#>

function Initialize-ProductModelsMonitorSku {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SiteId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LanguageCode},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Email},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SkuId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductModelsMonitorSku' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "SiteId" = ${SiteId}
            "LanguageCode" = ${LanguageCode}
            "Email" = ${Email}
            "SkuId" = ${SkuId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductModelsMonitorSku<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductModelsMonitorSku<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductModelsMonitorSku<PSCustomObject>
#>
function ConvertFrom-JsonToProductModelsMonitorSku {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductModelsMonitorSku' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductModelsMonitorSku
        $AllProperties = ("SiteId", "LanguageCode", "Email", "SkuId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "SiteId"))) { #optional property not found
            $SiteId = $null
        } else {
            $SiteId = $JsonParameters.PSobject.Properties["SiteId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "LanguageCode"))) { #optional property not found
            $LanguageCode = $null
        } else {
            $LanguageCode = $JsonParameters.PSobject.Properties["LanguageCode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Email"))) { #optional property not found
            $Email = $null
        } else {
            $Email = $JsonParameters.PSobject.Properties["Email"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "SkuId"))) { #optional property not found
            $SkuId = $null
        } else {
            $SkuId = $JsonParameters.PSobject.Properties["SkuId"].value
        }

        $PSO = [PSCustomObject]@{
            "SiteId" = ${SiteId}
            "LanguageCode" = ${LanguageCode}
            "Email" = ${Email}
            "SkuId" = ${SkuId}
        }

        return $PSO
    }

}

