#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A product feed.

.PARAMETER FeedId
The feed id.
.PARAMETER Name
The feed name.
.PARAMETER Url
The url to the feed.
.PARAMETER Layout
The name of the feed layout.
.PARAMETER Market
The market of the feed.
.PARAMETER Language
The language code of the feed.
.PARAMETER DefaultCurrency
The default currency for the market
.PARAMETER DefaultCountry
The default country for the market
.OUTPUTS

ProductModelsReadFeed<PSCustomObject>
#>

function Initialize-ProductModelsReadFeed {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${FeedId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Layout},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Market},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Language},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DefaultCurrency},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DefaultCountry}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductModelsReadFeed' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "FeedId" = ${FeedId}
            "Name" = ${Name}
            "Url" = ${Url}
            "Layout" = ${Layout}
            "Market" = ${Market}
            "Language" = ${Language}
            "DefaultCurrency" = ${DefaultCurrency}
            "DefaultCountry" = ${DefaultCountry}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductModelsReadFeed<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductModelsReadFeed<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductModelsReadFeed<PSCustomObject>
#>
function ConvertFrom-JsonToProductModelsReadFeed {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductModelsReadFeed' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductModelsReadFeed
        $AllProperties = ("FeedId", "Name", "Url", "Layout", "Market", "Language", "DefaultCurrency", "DefaultCountry")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "FeedId"))) { #optional property not found
            $FeedId = $null
        } else {
            $FeedId = $JsonParameters.PSobject.Properties["FeedId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["Name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Url"))) { #optional property not found
            $Url = $null
        } else {
            $Url = $JsonParameters.PSobject.Properties["Url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Layout"))) { #optional property not found
            $Layout = $null
        } else {
            $Layout = $JsonParameters.PSobject.Properties["Layout"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Market"))) { #optional property not found
            $Market = $null
        } else {
            $Market = $JsonParameters.PSobject.Properties["Market"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Language"))) { #optional property not found
            $Language = $null
        } else {
            $Language = $JsonParameters.PSobject.Properties["Language"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DefaultCurrency"))) { #optional property not found
            $DefaultCurrency = $null
        } else {
            $DefaultCurrency = $JsonParameters.PSobject.Properties["DefaultCurrency"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DefaultCountry"))) { #optional property not found
            $DefaultCountry = $null
        } else {
            $DefaultCountry = $JsonParameters.PSobject.Properties["DefaultCountry"].value
        }

        $PSO = [PSCustomObject]@{
            "FeedId" = ${FeedId}
            "Name" = ${Name}
            "Url" = ${Url}
            "Layout" = ${Layout}
            "Market" = ${Market}
            "Language" = ${Language}
            "DefaultCurrency" = ${DefaultCurrency}
            "DefaultCountry" = ${DefaultCountry}
        }

        return $PSO
    }

}

