#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A shipping fee for a product item.

.PARAMETER Market
The market that the shipping fee is applicable on.
.PARAMETER Country
The country that the shipping fee is applicable in.
.PARAMETER Service
The shipping service with the current fee.
.PARAMETER ServiceId
The shipping service id with the current fee.
.PARAMETER Fee
The shipping fee.
.OUTPUTS

ProductModelsReadShippingFee<PSCustomObject>
#>

function Initialize-ProductModelsReadShippingFee {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Market},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Country},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Service},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${ServiceId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${Fee}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductModelsReadShippingFee' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "Market" = ${Market}
            "Country" = ${Country}
            "Service" = ${Service}
            "ServiceId" = ${ServiceId}
            "Fee" = ${Fee}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductModelsReadShippingFee<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductModelsReadShippingFee<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductModelsReadShippingFee<PSCustomObject>
#>
function ConvertFrom-JsonToProductModelsReadShippingFee {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductModelsReadShippingFee' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductModelsReadShippingFee
        $AllProperties = ("Market", "Country", "Service", "ServiceId", "Fee")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Market"))) { #optional property not found
            $Market = $null
        } else {
            $Market = $JsonParameters.PSobject.Properties["Market"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Country"))) { #optional property not found
            $Country = $null
        } else {
            $Country = $JsonParameters.PSobject.Properties["Country"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Service"))) { #optional property not found
            $Service = $null
        } else {
            $Service = $JsonParameters.PSobject.Properties["Service"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ServiceId"))) { #optional property not found
            $ServiceId = $null
        } else {
            $ServiceId = $JsonParameters.PSobject.Properties["ServiceId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Fee"))) { #optional property not found
            $Fee = $null
        } else {
            $Fee = $JsonParameters.PSobject.Properties["Fee"].value
        }

        $PSO = [PSCustomObject]@{
            "Market" = ${Market}
            "Country" = ${Country}
            "Service" = ${Service}
            "ServiceId" = ${ServiceId}
            "Fee" = ${Fee}
        }

        return $PSO
    }

}

