#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER LazyLoadConfiguration
No description available.
.PARAMETER LazyLoadCollectionConfigurations
No description available.
.PARAMETER WidgetRestrictions
No description available.
.PARAMETER ContainerRestrictions
No description available.
.OUTPUTS

SystemNullableValidationConfiguration<PSCustomObject>
#>

function Initialize-SystemNullableValidationConfiguration {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${LazyLoadConfiguration},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${LazyLoadCollectionConfigurations},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Collections.Hashtable]
        ${WidgetRestrictions},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ContainerRestrictions}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => SystemNullableValidationConfiguration' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "LazyLoadConfiguration" = ${LazyLoadConfiguration}
            "LazyLoadCollectionConfigurations" = ${LazyLoadCollectionConfigurations}
            "WidgetRestrictions" = ${WidgetRestrictions}
            "ContainerRestrictions" = ${ContainerRestrictions}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SystemNullableValidationConfiguration<PSCustomObject>

.DESCRIPTION

Convert from JSON to SystemNullableValidationConfiguration<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SystemNullableValidationConfiguration<PSCustomObject>
#>
function ConvertFrom-JsonToSystemNullableValidationConfiguration {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => SystemNullableValidationConfiguration' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SystemNullableValidationConfiguration
        $AllProperties = ("LazyLoadConfiguration", "LazyLoadCollectionConfigurations", "WidgetRestrictions", "ContainerRestrictions")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "LazyLoadConfiguration"))) { #optional property not found
            $LazyLoadConfiguration = $null
        } else {
            $LazyLoadConfiguration = $JsonParameters.PSobject.Properties["LazyLoadConfiguration"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "LazyLoadCollectionConfigurations"))) { #optional property not found
            $LazyLoadCollectionConfigurations = $null
        } else {
            $LazyLoadCollectionConfigurations = $JsonParameters.PSobject.Properties["LazyLoadCollectionConfigurations"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "WidgetRestrictions"))) { #optional property not found
            $WidgetRestrictions = $null
        } else {
            $WidgetRestrictions = $JsonParameters.PSobject.Properties["WidgetRestrictions"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ContainerRestrictions"))) { #optional property not found
            $ContainerRestrictions = $null
        } else {
            $ContainerRestrictions = $JsonParameters.PSobject.Properties["ContainerRestrictions"].value
        }

        $PSO = [PSCustomObject]@{
            "LazyLoadConfiguration" = ${LazyLoadConfiguration}
            "LazyLoadCollectionConfigurations" = ${LazyLoadCollectionConfigurations}
            "WidgetRestrictions" = ${WidgetRestrictions}
            "ContainerRestrictions" = ${ContainerRestrictions}
        }

        return $PSO
    }

}

