#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A variant group for a collection of related variants.

.PARAMETER GroupId
The id of variant goup.
.PARAMETER Name
The optional internal name of the variant group.
.PARAMETER CollapseInLists
Determine visibility of non-main products of this group in lists.
.PARAMETER MainProductId
The main product of this group. If the group is collapsed in lists, this will be the only visible product.
.PARAMETER ProductIds
The product ids of the variants that belong to this group.
.PARAMETER Products
Products belonging to the Variant group. Only included when parameter ""include"" is supplied in the query string
.OUTPUTS

VariantModelsReadVariantGroup<PSCustomObject>
#>

function Initialize-VariantModelsReadVariantGroup {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${GroupId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${CollapseInLists},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MainProductId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${ProductIds},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Products}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => VariantModelsReadVariantGroup' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "GroupId" = ${GroupId}
            "Name" = ${Name}
            "CollapseInLists" = ${CollapseInLists}
            "MainProductId" = ${MainProductId}
            "ProductIds" = ${ProductIds}
            "Products" = ${Products}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VariantModelsReadVariantGroup<PSCustomObject>

.DESCRIPTION

Convert from JSON to VariantModelsReadVariantGroup<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VariantModelsReadVariantGroup<PSCustomObject>
#>
function ConvertFrom-JsonToVariantModelsReadVariantGroup {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => VariantModelsReadVariantGroup' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VariantModelsReadVariantGroup
        $AllProperties = ("GroupId", "Name", "CollapseInLists", "MainProductId", "ProductIds", "Products")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "GroupId"))) { #optional property not found
            $GroupId = $null
        } else {
            $GroupId = $JsonParameters.PSobject.Properties["GroupId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["Name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "CollapseInLists"))) { #optional property not found
            $CollapseInLists = $null
        } else {
            $CollapseInLists = $JsonParameters.PSobject.Properties["CollapseInLists"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "MainProductId"))) { #optional property not found
            $MainProductId = $null
        } else {
            $MainProductId = $JsonParameters.PSobject.Properties["MainProductId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ProductIds"))) { #optional property not found
            $ProductIds = $null
        } else {
            $ProductIds = $JsonParameters.PSobject.Properties["ProductIds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Products"))) { #optional property not found
            $Products = $null
        } else {
            $Products = $JsonParameters.PSobject.Properties["Products"].value
        }

        $PSO = [PSCustomObject]@{
            "GroupId" = ${GroupId}
            "Name" = ${Name}
            "CollapseInLists" = ${CollapseInLists}
            "MainProductId" = ${MainProductId}
            "ProductIds" = ${ProductIds}
            "Products" = ${Products}
        }

        return $PSO
    }

}

