#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OrderModelsAddress' {
    Context 'OrderModelsAddress' {
        It 'Initialize-OrderModelsAddress' {
            # a simple test to create an object
            #$NewObject = Initialize-OrderModelsAddress -Company "TEST_VALUE" -CareOf "TEST_VALUE" -State "TEST_VALUE" -Country "TEST_VALUE" -FirstName "TEST_VALUE" -LastName "TEST_VALUE" -Email "TEST_VALUE" -AddressLine1 "TEST_VALUE" -AddressLine2 "TEST_VALUE" -AddressLine3 "TEST_VALUE" -Zip "TEST_VALUE" -City "TEST_VALUE" -Phone "TEST_VALUE" -Mobile "TEST_VALUE" -EntryCode "TEST_VALUE"
            #$NewObject | Should -BeOfType OrderModelsAddress
            #$NewObject.property | Should -Be 0
        }
    }
}
