#
# Geins Management API
#  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
# Version: v1.7
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductModelsReadProduct' {
    Context 'ProductModelsReadProduct' {
        It 'Initialize-ProductModelsReadProduct' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductModelsReadProduct -ProductId "TEST_VALUE" -ArticleNumber "TEST_VALUE" -Names "TEST_VALUE" -DateCreated "TEST_VALUE" -DateUpdated "TEST_VALUE" -Active "TEST_VALUE" -PurchasePrice "TEST_VALUE" -PurchasePriceCurrency "TEST_VALUE" -ShortTexts "TEST_VALUE" -LongTexts "TEST_VALUE" -TechTexts "TEST_VALUE" -Items "TEST_VALUE" -Prices "TEST_VALUE" -Categories "TEST_VALUE" -Images "TEST_VALUE" -BrandId "TEST_VALUE" -BrandName "TEST_VALUE" -SupplierId "TEST_VALUE" -SupplierName "TEST_VALUE" -ParameterValues "TEST_VALUE" -Variants "TEST_VALUE" -Markets "TEST_VALUE" -Vat "TEST_VALUE" -PrimaryImage "TEST_VALUE" -FreightClassId "TEST_VALUE" -IntrastatCode "TEST_VALUE" -CountryOfOrigin "TEST_VALUE" -VariantGroupId "TEST_VALUE" -VatId "TEST_VALUE" -ExternalId "TEST_VALUE" -ActivationDate "TEST_VALUE" -Feeds "TEST_VALUE" -Urls "TEST_VALUE" -MainCategoryId "TEST_VALUE" -RelatedProducts "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductModelsReadProduct
            #$NewObject.property | Should -Be 0
        }
    }
}
